# Generated by Django 4.2.1 on 2023-06-02 08:18

from django.db import migrations, models
import guests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='files')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(validators=[guests.models.UpcomingInput.only_int])),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Coming'), (2, 'Not Coming')], default=2)),
                ('incoming_timestamps', models.DateTimeField()),
            ],
        ),
    ]
