# Generated by Django 4.2.1 on 2023-05-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='upcominginput',
            name='phone_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='upcominginput',
            name='status',
            field=models.IntegerField(choices=[(1, 'Coming'), (2, 'Not Coming')], default=2),
        ),
    ]
