# Generated by Django 4.2.1 on 2023-06-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcominginput',
            name='incoming_timestamps',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
