# Generated by Django 4.2.1 on 2023-06-02 06:08

from django.db import migrations, models
import guests.models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_alter_guest_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcominginput',
            name='phone_number',
            field=models.CharField(validators=[guests.models.UpcomingInput.only_int]),
        ),
    ]
